Repository TUM-Dev/Campus-Android, pull requests merged in 2018-05, with the labels that each got.

#797 put all card attributes into a style
  app/src/main/res/layout/card_eduroam.xml
  app/src/main/res/layout/card_eduroam_fix.xml
  app/src/main/res/layout/card_first_use1.xml
  app/src/main/res/layout/card_first_use2.xml
  app/src/main/res/layout/card_item.xml
  app/src/main/res/layout/card_list_header.xml
  app/src/main/res/layout/card_login_promt.xml
  app/src/main/res/layout/card_news_film_item.xml
  app/src/main/res/layout/card_news_item.xml
  app/src/main/res/layout/card_next_lecture_item.xml
  app/src/main/res/layout/card_no_internet.xml
  app/src/main/res/layout/card_price_line.xml
  app/src/main/res/layout/card_restore.xml
  app/src/main/res/layout/card_support.xml
  app/src/main/res/layout/card_top_news.xml
  app/src/main/res/values/styles.xml
Labels: review

#798 don't try to load image if path is empty
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/TopNewsCard.java
Labels: review

#787 Cleanup gradle files and move configurations to separate folders
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/TUMOnlineConst.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsSourcesDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/model/News.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/model/NewsSources.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/CacheManager.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/FileUtils.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/NetUtils.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/sync/SyncManager.java
  crowdin.yml
  gradle/config/checkstyle.xml
  gradle/config/detekt-config.yml
  gradle/config/excludeBugsFilter.xml
  gradle/config/lint.xml
  gradle/config/pmd-ruleset.xml
  gradle/scripts/checkstyle.gradle
  gradle/scripts/detekt.gradle
  gradle/scripts/findbugs.gradle
  gradle/scripts/jacoco.gradle
  gradle/scripts/pmd.gradle
  gradle/scripts/testLogging.gradle
  testApp.sh
Labels: review

#811 Replace old SupportCard links with Material design buttons
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/SupportCard.java
  app/src/main/res/drawable-mdpi/ic_facebook_white_transparent.xml
  app/src/main/res/drawable-nodpi/facebook.png
  app/src/main/res/drawable/github.xml
  app/src/main/res/drawable/ic_mail_outline.xml
  app/src/main/res/layout/activity_information.xml
  app/src/main/res/layout/card_support.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: User experience :rofl:, review

#796 Migrate services to Kotlin
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/wifimeasurement/model/WifiMeasurement.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/model/Location.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/StartupActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/java/de/tum/in/tumcampusapp/service/BackgroundService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/BackgroundService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/FavoriteDishAlarmScheduler.java
  app/src/main/java/de/tum/in/tumcampusapp/service/FavoriteDishAlarmScheduler.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/FcmReceiverService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/FcmReceiverService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/FillCacheService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/FillCacheService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/GcmIdentificationService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/GcmIdentificationService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/GeofencingRegistrationService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/GeofencingStartupReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/GeofencingUpdateReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/MensaWidgetService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/MensaWidgetService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/NetworkChangeReceiver.java
  app/src/main/java/de/tum/in/tumcampusapp/service/NetworkChangeReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/ScanResultsAvailableReceiver.java
  app/src/main/java/de/tum/in/tumcampusapp/service/ScanResultsAvailableReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/SendWifiMeasurementService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/SendWifiMeasurementService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/SilenceService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/SilenceService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/StartSyncReceiver.java
  app/src/main/java/de/tum/in/tumcampusapp/service/StartSyncReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/WifiScanHandler.java
  app/src/main/java/de/tum/in/tumcampusapp/service/WifiScanHandler.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/GeneralExt.kt
Labels: review

#800 feedback layout
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/feedback/FeedbackActivity.java
  app/src/main/res/layout/activity_feedback.xml
  app/src/main/res/layout/feedback_thumb.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Suggestion :telescope:, review

#826 Qr code activity
  .idea/codeStyleSettings.xml
  .idea/fileTemplates/includes/File Header.java
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForAccessingTumOnline.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/feedback/FeedbackActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/show_ticket.java
  app/src/main/res/drawable-nodpi/qrcodedemo.png
  app/src/main/res/drawable/feedback_rounded_background.xml
  app/src/main/res/drawable/ic_action_info_blue.xml
  app/src/main/res/drawable/ic_refresh_white.xml
  app/src/main/res/layout/activity_feedback.xml
  app/src/main/res/layout/activity_show_ticket.xml
  app/src/main/res/layout/activity_tuitionfees.xml
  app/src/main/res/layout/feedback_thumb.xml
  app/src/main/res/menu/menu_sync_calendar.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: review

#827 Feature/ticketsale
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoDetailsFragment.java
  app/src/main/res/layout-sw350dp/kino_header.xml
  app/src/main/res/layout/kino_header.xml
Labels: review

#829 Qr code activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/show_ticket.java
  app/src/main/res/values/strings.xml
Labels: review

#836 prevent users from sending empty or accidental feedback
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/feedback/FeedbackActivity.java
  app/src/main/res/layout/activity_feedback.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#816 768 user custom filters calendar
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/LimitPickerDialog.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/LimitPickerDialogListener.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/layout/dialog_calendar_filter_limits.xml
  app/src/main/res/menu/menu_sync_calendar.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review
