Repository TUM-Dev/Campus-Android, pull requests merged in 2018-12, with the labels that each got.

#1226 Tweak design in kino details view
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/model/Kino.kt
  app/src/main/res/layout/fragment_kinodetails_section.xml
  app/src/test/java/de/tum/in/tumcampusapp/activities/KinoActivityTest.kt
Labels: User experience :ok_hand:

#1231 Refactor CafeteriaActivity and view model
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ProgressActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaNotificationProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/activity/CafeteriaActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaDetailsSectionFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaDetailsSectionsPagerAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/model/Cafeteria.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/repository/CafeteriaLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/repository/CafeteriaRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/widget/MensaWidget.java
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Extensions.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/LocationHelper.kt
Labels: Improvement

#1233 Fix number formatting issue in Kino
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/model/Kino.kt
Labels: Bug :bug:

#1234 Introduce Dagger in some components
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/App.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/AuthenticationManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/BaseActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/activity/CafeteriaActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaMenuManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaDetailsSectionFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/di/CafeteriaComponent.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/di/CafeteriaModule.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/repository/CafeteriaLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/repository/CafeteriaRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/TopNewsCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/TopNewsStore.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/TopNewsViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/model/NewsAlert.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/repository/TopNewsRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/MainActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/MainActivityViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoDetailsViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/di/KinoComponent.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/di/KinoModule.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/repository/KinoRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/di/AppComponent.kt
  app/src/main/java/de/tum/in/tumcampusapp/di/AppModule.kt
  app/src/main/java/de/tum/in/tumcampusapp/di/Injector.kt
  app/src/main/java/de/tum/in/tumcampusapp/di/ViewModelFactory.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/di/DownloadComponent.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/di/DownloadModule.kt
Labels: Improvement

#1230 Adds card that displays an update note
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/StartupActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardsRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/updatenote/UpdateNoteCard.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/updatenote/UpdateNoteController.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/updatenote/model/UpdateNote.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/layout/card_update_note.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Feature :tada:

#1238 Prevent crash when Intent can’t be handled
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/person/PersonContactItemsAdapter.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Bug :bug:

#1240 Hide cards if no content is available
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.kt
Labels: Improvement

#1239 Update calendar view
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarDetailsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/EventColorProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/IntegratedCalendarEvent.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/LimitPickerDialog.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/LimitPickerDialogListener.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/WidgetCalendarItem.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/model/CalendarItem.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/widget/TimetableWidgetService.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/roomfinder/WeekViewFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/ColorUtils.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/FontUtils.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/fragment_day_view.xml
Labels: Improvement
