Repository TUM-Dev/Campus-Android, pull requests merged in 2018-10, with the labels that each got.

#1111 Beta 3 fixes
  app/src/main/java/de/tum/in/tumcampusapp/api/app/AuthenticationManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavStartActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/service/FcmIdentificationService.kt
  app/src/main/res/layout/card_events_item.xml
  app/src/main/res/layout/card_news_film_item.xml
  app/src/main/res/layout/card_news_item.xml
Labels: Bug :bug:

#1114 Hide options button in cards if not in MainActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsInflater.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsViewHolder.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventCard.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/adapter/EventsAdapter.java
  app/src/main/res/layout/card_events_item.xml
  app/src/main/res/layout/card_news_film_item.xml
  app/src/main/res/layout/card_news_item.xml
Labels: Improvement

#1136 Fix scroll for information and cafeteria activity
  app/src/main/res/layout/activity_information.xml
  app/src/main/res/layout/fragment_cafeteriadetails_section.xml
Labels: Bug :bug:

#1138 Fix ActivityNotFoundException in InfoActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/InformationActivity.kt
  app/src/main/res/values/strings.xml
Labels: Bug :bug:

#1107 Redo StudyRoomsActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/adapter/GridEqualSpacingDecoration.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/openinghour/OpeningHoursDetailFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomAdapter.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupDetailsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomViewHolder.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsPagerAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsPagerAdapter.kt
  app/src/main/res/layout/card_header_details_button.xml
Labels: User experience :ok_hand:

#1142 Fixes for 2.0 release
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForAccessingTumOnline.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearchingTumOnline.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvApiService.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvDepartureList.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/Departure.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/WidgetDepartures.kt
  app/src/main/res/drawable/info_box_background.xml
  app/src/main/res/layout/activity_events.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvDepartureListTest.java
Labels: Bug :bug:

#1135 Custom event: DatePicker one month off
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
Labels: Bug :bug:

#1166 Prevent IllegalStateException (openEvent)
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
Labels: Bug :bug:

#1163 Catch on Card creation
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/TopNewsCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/StartupActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardsRepository.kt
Labels: Bug :bug:

#1167 Refactor ProgressActivity and related improvements
  app/src/main/java/de/tum/in/tumcampusapp/api/app/ApiHelper.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/AuthenticationManager.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TumHttpLoggingInterceptor.java
  app/src/main/java/de/tum/in/tumcampusapp/api/cafeteria/CafeteriaAPIClient.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/TUMOnlineClient.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/converters/DateTimeConverter.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/ImageViewTouchFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForAccessingTumCabe.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForAccessingTumOnline.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForAccessingTumOnline.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForDownloadingExternal.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearching.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearchingInBackground.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearchingTumOnline.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearchingTumOnline.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ProgressActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/adapter/GridEqualSpacingDecoration.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/adapter/SimpleStickyListHeadersAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/locations/LocationManager.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/lectures/activity/LecturesAppointmentsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/lectures/activity/LecturesDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/lectures/activity/LecturesPersonalActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/roomfinder/RoomFinderDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/barrierfree/BarrierFreeFacilitiesActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/barrierfree/BarrierFreeFacilitiesActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/AddChatMemberActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studycard/CardsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studycard/CardsDetailActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studycard/CardsQuizActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studycard/StudyCardListAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studycard/model/CardActivityState.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studycard/model/StudyCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupManager.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportationActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportationDetailsActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvClient.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetConfigureActivity.kt
  app/src/main/res/layout/activity_barrier_free_facilities.xml
Labels: Improvement

#1164 Improve display of upcoming events via CalendarDetailsFragment
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarDetailsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/NextLectureCardViewHolder.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/NextLectureView.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/model/CalendarItem.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/card/CardViewHolder.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/drawable/ic_baseline_open_in_new.xml
  app/src/main/res/drawable/ic_outline_location_on_24px_light_blue.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/calendar_location_text.xml
  app/src/main/res/layout/card_next_lecture_item.xml
  app/src/main/res/layout/fragment_calendar_details.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Improvement

#1165 Fix Exception caused by too many alarms
  app/schemas/de.tum.in.tumcampusapp.database.TcaDb/2.json
  app/src/main/java/de/tum/in/tumcampusapp/component/notifications/NotificationScheduler.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/notifications/persistence/ActiveAlarm.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/notifications/persistence/ActiveAlarmsDao.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/notifications/receivers/NotificationReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/java/de/tum/in/tumcampusapp/database/migrations/Migration1to2.kt
Labels: Bug :bug:

#1184 Fix bug where events of last day in month were not displayed
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/DateTimeUtils.kt
Labels: Bug :bug:

#1186 Fix borked android.support -> androidx mirgation
  app/src/main/res/xml/settings.xml
Labels: Bug :bug:
