Repository TUM-Dev/Campus-Android, pull requests merged in 2018-09, with the labels that each got.

#908 Check which ids have been uploaded and upload missing ones, part 2
  app/src/main/java/de/tum/in/tumcampusapp/api/app/AuthenticationManager.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/model/DeviceUploadFcmToken.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/model/DeviceVerification.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/model/ObfuscatedIdsUpload.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/model/TUMCabeVerification.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/model/UploadStatus.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/AddChatMemberActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatMessageViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatNotification.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatRoomController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/model/ChatVerification.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/repository/ChatMessageRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavCheckTokenActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavExtrasActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studycard/CardsDetailActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/FcmIdentificationService.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#1030 do MVV calls with RXJava
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearching.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVSymbolView.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportationActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportationActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportationDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportationDetailsActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvApiService.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvClient.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/WidgetDepartures.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetConfigureActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetConfigureActivity.kt
Labels: review

#1057 Unify cafeteria and favorite dish notifications
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaNotificationProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaNotificationSettings.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/FavoriteFoodAlarmStorage.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaMenuManager.java
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/java/de/tum/in/tumcampusapp/service/FavoriteDishAlarmScheduler.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Improvement, review

#1064 Prevent notifications about past events
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/model/Event.kt
Labels: Bug :bug:

#1076 Fix NullPointerException in MVVWidget
  app/src/main/java/de/tum/in/tumcampusapp/api/app/AuthenticationManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidget.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetConfigureActivity.kt
Labels: Bug :bug:

#1077 Improve MVV card and details activity
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/DepartureView.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/StationResult.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetService.java
  app/src/main/res/layout/activity_transportation_detail.xml
  app/src/main/res/layout/card_mvv.xml
  app/src/main/res/layout/departure_line_big.xml
  app/src/main/res/layout/departure_line_small.xml
  app/src/main/res/layout/departure_line_widget.xml
Labels: Improvement

#1079 Fix problem where StartupActivity would not finish
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/StartupActivity.java
Labels: Bug :bug:

#1080 Add logout option and update settings design
  app/src/main/java/de/tum/in/tumcampusapp/component/other/settings/SettingsFragment.java
  app/src/main/res/drawable/ic_outline_exit_to_app_24px.xml
  app/src/main/res/drawable/ic_outline_group_add_24px.xml
  app/src/main/res/drawable/ic_outline_phonelink_ring_24px.xml
  app/src/main/res/drawable/ic_outline_update_24px.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/settings.xml
Labels: Improvement

#1086 Fix problem that resulted in a Bad Request to tickets API
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
Labels: Bug :bug:

#1083 Make UI improvements in CreateEventActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/res/layout/activity_create_event.xml
Labels: Improvement

#1090 Fix NetworkOnMainThreadException
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatRoomsActivity.java
Labels: Bug :bug:

#1088 Fix JSON parsing bug in lecture appointments
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/converters/DateConverter.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/converters/DateTimeConverter.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/model/Exam.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/model/Tuition.kt
Labels: Bug :bug:

#1089 Add null check in CalendarActivity to prevent IllegalArgumentException
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/TUMOnlineAPIService.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/TUMOnlineClient.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/model/EventsResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/CacheManager.kt
Labels: Bug :bug:

#1092 Tweak display of duration until departure in DepartureView
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/DepartureView.java
Labels: Improvement

#1094 Add more calendar improvements
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_create_event.xml
  app/src/main/res/layout/card_next_lecture_item.xml
  app/src/main/res/menu/menu_sync_calendar.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Improvement

#1087 Fix several problems in chat
  app/src/main/java/de/tum/in/tumcampusapp/api/app/ChaosMonkeyInterceptor.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/AddChatMemberActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatMessageDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatMessageViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatNotification.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/adapter/ChatHistoryAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/adapter/ChatRoomListAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/model/ChatMember.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/model/ChatMessage.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/repository/ChatMessageLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/repository/ChatMessageRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/SendMessageService.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Utils.java
  app/src/main/res/drawable/bg_message_incoming.xml
  app/src/main/res/drawable/bg_message_outgoing.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_chat_history_row_incoming.xml
  app/src/main/res/layout/activity_chat_history_row_outgoing.xml
  app/src/main/res/layout/activity_chat_rooms.xml
  app/src/main/res/layout/card_price_line.xml
  app/src/main/res/menu/menu_activity_chat.xml
  app/src/main/res/menu/menu_activity_chat_rooms.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Improvement

#1096 Fix event creation crash in v2.0 beta 2
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsFragment.kt
  app/src/main/res/values-v27/styles.xml
Labels: Bug :bug:

#1099 Fix build error
  app/src/main/res/drawable/meal_alcohol.xml
  app/src/main/res/drawable/meal_beef.xml
  app/src/main/res/drawable/meal_pork.xml
  app/src/main/res/drawable/meal_vegan.xml
  app/src/main/res/drawable/meal_veggie.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: Bug :bug:

#1101 Switch status bar to lighter gray
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
Labels: Improvement

#1103 Fixes in MVV widget
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearching.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/DepartureView.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVSymbol.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVSymbolView.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetConfigureActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetService.java
  app/src/main/res/layout/activity_mvv_widget_configure.xml
  app/src/main/res/layout/mvv_widget.xml
Labels: Bug :bug:, Improvement

#1104 Improve offline experience
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/app/ConnectivityInterceptor.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/Helper.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/exception/NoNetworkConnectionException.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForAccessingTumOnline.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearchingTumOnline.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ProgressActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarDetailsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeeManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavCheckTokenActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsPagerAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportationActivity.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_grades.xml
  app/src/main/res/layout/activity_tuitionfees.xml
  app/src/main/res/layout/layout_all_errors.xml
Labels: Bug :bug:, Improvement
