Repository TUM-Dev/Campus-Android, pull requests merged in 2018-07, with the labels that each got.

#941 Improve eventdetail ui
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsFragment.java
  app/src/main/res/drawable/buttonshape_ticket.xml
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/drawable/textshape_ticket.xml
  app/src/main/res/layout/event_footer.xml
  app/src/main/res/layout/event_header.xml
  app/src/main/res/layout/fragment_kinodetails_section.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: FeatureBranch, review

#938 implemented display of ticket types in BuyTicketActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/res/layout/activity_buy_ticket.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: FeatureBranch, review

#901 Rework WiFi scanning
  app/src/main/java/de/tum/in/tumcampusapp/service/BackgroundService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/ScanResultsAvailableReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/WifiScanHandler.kt
Labels: review

#939 Added color (accent) attribute to all notification creation
  app/src/main/java/de/tum/in/tumcampusapp/component/notifications/NotificationsProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/general/Update.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarNotificationsProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesNotificationsProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/alarm/AlarmNotification.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaNotificationsProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatNotification.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsNotificationsProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportNotificationsProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/FavoriteDishAlarmScheduler.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/ScanResultsAvailableReceiver.kt
Labels: FeatureBranch, Improvement

#900 enable StrictMode in DEBUG builds
  app/src/main/java/de/tum/in/tumcampusapp/App.java
Labels: review

#944 Ticket Sale: credit card checkout
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketEphemeralKeyProvider.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketPaymentSelectActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/layout/activity_payment_stripe.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: FeatureBranch, Work in progress, review

#946 adjusted event details layout to fit 16:9 image
  app/src/main/res/layout/event_footer.xml
  app/src/main/res/layout/event_header.xml
Labels: review

#954 Fix crash in BackgroundService
  app/src/main/java/de/tum/in/tumcampusapp/service/BackgroundService.kt
Labels: Bug :bug:, review

#957 Simplify news image loading
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/model/NewsSources.kt
Labels: Improvement, review

#958 Fix NoSuchMethodError in Exam
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/model/Exam.kt
Labels: Bug :bug:, review

#956 Add network resiliency testing interceptor and improve error handling
  app/src/main/java/de/tum/in/tumcampusapp/api/app/ChaosMonkeyInterceptor.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/Helper.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/exception/ChaosMonkeyException.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/TUMOnlineRequest.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForLoadingInBackground.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/ActivityForSearchingInBackground.java
Labels: Bug :bug:, High Priority :fire_engine:, Improvement, review

#960 Invert Chaos logic
  app/src/main/java/de/tum/in/tumcampusapp/api/app/Helper.java
Labels: review

#948 As/replace mocks in stripe checkout
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/model/ChatVerification.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketEphemeralKeyProvider.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Event.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/TicketReservationResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/TicketSuccessResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/TicketType.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/EphimeralKey.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservation.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservationCancelation.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservationResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketSuccessResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/res/layout/activity_buy_ticket.xml
  app/src/main/res/layout/event_header.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: FeatureBranch, review

#962 Add version information about BuildConfig status
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/InformationActivity.kt
Labels: review

#757 Add Fastlane to automate deployments
  .gitignore
  Gemfile
  Gemfile.lock
  app/build.gradle
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/metadata/android/de-DE/changelogs/512.txt
  fastlane/metadata/android/de-DE/changelogs/513.txt
  fastlane/metadata/android/de-DE/changelogs/514.txt
  fastlane/metadata/android/de-DE/changelogs/515.txt
  fastlane/metadata/android/de-DE/changelogs/516.txt
  fastlane/metadata/android/de-DE/changelogs/517.txt
  fastlane/metadata/android/de-DE/changelogs/518.txt
  fastlane/metadata/android/de-DE/changelogs/519.txt
  fastlane/metadata/android/de-DE/changelogs/520.txt
  fastlane/metadata/android/de-DE/changelogs/521.txt
  fastlane/metadata/android/de-DE/changelogs/522.txt
  fastlane/metadata/android/de-DE/full_description.txt
  fastlane/metadata/android/de-DE/images/feature.png
  fastlane/metadata/android/de-DE/images/icon.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/1.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/10.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/3.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/4.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/5.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/6.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/8.png
  fastlane/metadata/android/de-DE/images/phoneScreenshots/9.png
  fastlane/metadata/android/de-DE/images/sevenInchScreenshots/11.png
  fastlane/metadata/android/de-DE/images/sevenInchScreenshots/2.png
  fastlane/metadata/android/de-DE/images/tenInchScreenshots/1.png
  fastlane/metadata/android/de-DE/images/tenInchScreenshots/7.png
  fastlane/metadata/android/de-DE/short_description.txt
  fastlane/metadata/android/de-DE/title.txt
  fastlane/metadata/android/de-DE/video.txt
Labels: Work in progress, review

#894 Ticket sale: implement ticket check
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/ConfirmCheckInFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketScanActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/EphimeralKey.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservation.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketValidityRequest.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketValidityResponse.java
  app/src/main/res/layout/activity_ticket_scan.xml
  app/src/main/res/layout/fragment_confirm_check_in.xml
  app/src/main/res/layout/ticket_buyer_name_display.xml
  app/src/main/res/values/strings.xml
Labels: FeatureBranch, review

#964 implemented first version of adding event to tum calendar
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/layout/dialog_add_to_calendar.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#963 added a view additional changes forgotten in previous PR
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/TicketType.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#961 also allow ISO dates for DateSerializer
  app/src/main/java/de/tum/in/tumcampusapp/api/app/DateSerializer.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/adapter/ChatRoomListAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
Labels: Bug :bug:, review

#974 As/949 remove email from stripe request
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketEphemeralKeyProvider.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/EphimeralKey.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketPurchaseStripe.kt
Labels: review

#975 As/include available ticket count
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservationResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketStatus.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#976 As/adapt events add endtime
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Event.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/Converters.kt
Labels: review

#985 Fix link in TuitionFeesActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesActivity.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Bug :bug:, review

#981 As/refactor ticket sale
  .idea/codeStyleSettings.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/ConfirmCheckInFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketEphemeralKeyProvider.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketScanActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/EventDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/EventsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/TicketPaymentSelectActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/adapter/EventDetailsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/adapter/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Event.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Ticket.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/TicketType.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservationCancelation.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservationResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketValidityRequest.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketValidityResponse.java
  app/src/main/res/layout/activity_ticket_scan.xml
  app/src/main/res/layout/fragment_confirm_check_in.xml
  app/src/main/res/layout/ticket_buyer_name_display.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#984 Ticket Sale: fixed some leftovers
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventFragment.java
  app/src/main/res/layout-sw350dp/kino_header.xml
  app/src/main/res/layout/kino_header.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#994 Ticket Sale: implemented Pull-Refresh for Ticket Counter
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsFragment.java
  app/src/main/res/layout/event_footer.xml
  app/src/main/res/layout/fragment_event_details.xml
Labels: review

#998 Fix crash in card widget
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsCard.java
Labels: Bug :bug:, review

#990 Fix cases where text field cursor was light on light background
  app/src/main/res/layout/activity_setup_eduroam.xml
  app/src/main/res/layout/activity_wiznav_start.xml
Labels: Improvement, review

#1001 Fix crash in MVVWidgetConfigureActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetConfigureActivity.java
Labels: Bug :bug:, review

#1002 Fix wrong end time and timezone in calendar export
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/model/CalendarItem.kt
Labels: Bug :bug:, review

#995 Fix NotificationAwareCard crash
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVCard.java
Labels: Bug :bug:, review

#989 remove changes from database json and remove unnecessary dependency s…
  app/build.gradle
  app/schemas/de.tum.in.tumcampusapp.database.TcaDb/10.json
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#997 Ticket Sale: integrated EventCard to CardView
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardsRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/adapter/EventsAdapter.java
Labels: review

#988 Update libraries
  app/build.gradle
  build.gradle
Labels: review

#992 Remove maxHeight on image view to make it adapt to image aspect ratio
  app/src/main/res/layout/card_top_news.xml
Labels: Improvement, review

#996 Properly finish setup wizard
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavCheckTokenActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavExtrasActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavStartActivity.java
Labels: Improvement, review

#993 Add loading indicator to MainActivity on first load
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/MainActivity.java
Labels: Improvement, User experience :ok_hand:, review

#942 Update widgets
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/widget/CardsWidget.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/widget/CardsWidgetConfigureActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/widget/CardsWidgetService.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/NextLectureCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/widget/TimetableWidget.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/widget/TimetableWidgetConfigureActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/widget/TimetableWidgetService.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaMenuCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/widget/MensaRemoteViewFactory.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/widget/MensaWidget.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatMessagesCard.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/eduroam/EduroamCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/TopNewsViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/card/Card.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/Departure.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/WidgetDepartures.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidget.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/widget/MVVWidgetService.java
  app/src/main/java/de/tum/in/tumcampusapp/service/MensaWidgetService.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/NetUtils.java
  app/src/main/res/color/widget_header_color.xml
  app/src/main/res/drawable/rounded_corners_background.xml
  app/src/main/res/drawable/widget_content_rounded_corners_background.xml
  app/src/main/res/drawable/widget_header_rounded_corners_background.xml
  app/src/main/res/layout/activity_mvv_widget_configure.xml
  app/src/main/res/layout/cards_widget.xml
  app/src/main/res/layout/cards_widget_card.xml
  app/src/main/res/layout/cards_widget_configure.xml
  app/src/main/res/layout/departure_line_widget.xml
  app/src/main/res/layout/mensa_widget.xml
  app/src/main/res/layout/mensa_widget_item.xml
  app/src/main/res/layout/mvv_widget.xml
  app/src/main/res/layout/timetable_widget.xml
  app/src/main/res/layout/timetable_widget_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/cards_widget_info.xml
  app/src/main/res/xml/mensa_widget_info.xml
  app/src/main/res/xml/mvv_widget_info.xml
  app/src/main/res/xml/timetable_widget_info.xml
Labels: review

#952 Update window chrome
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/barrierfree/BarrierFreeInfoActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/InformationActivity.kt
  app/src/main/res/layout-land/activity_grades.xml
  app/src/main/res/layout/activity_barrier_free_facilities.xml
  app/src/main/res/layout/activity_barrier_free_info.xml
  app/src/main/res/layout/activity_barrier_free_list_info.xml
  app/src/main/res/layout/activity_cafeteria.xml
  app/src/main/res/layout/activity_cafeteria_notification_settings.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_chat_rooms.xml
  app/src/main/res/layout/activity_create_event.xml
  app/src/main/res/layout/activity_feedback.xml
  app/src/main/res/layout/activity_grades.xml
  app/src/main/res/layout/activity_information.xml
  app/src/main/res/layout/activity_kino.xml
  app/src/main/res/layout/activity_lectures.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_news.xml
  app/src/main/res/layout/activity_openinghours_twopane.xml
  app/src/main/res/layout/activity_openinghoursdetails.xml
  app/src/main/res/layout/activity_person_details.xml
  app/src/main/res/layout/activity_person_search.xml
  app/src/main/res/layout/activity_roomfinder.xml
  app/src/main/res/layout/activity_roomfinderdetails.xml
  app/src/main/res/layout/activity_study_rooms.xml
  app/src/main/res/layout/activity_transportation.xml
  app/src/main/res/layout/activity_transportation_detail.xml
  app/src/main/res/layout/activity_tuitionfees.xml
  app/src/main/res/layout/activity_user_preferences.xml
  app/src/main/res/layout/drawer_header.xml
  app/src/main/res/layout/navigation_drawer.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: User experience :ok_hand:

#1000 Ticket Sale: pull-to-refresh to update ticket and event data from server
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
Labels: review

#1021 Add Firebase-Core to prevent rare crash
  app/build.gradle
Labels: Bug :bug:, review

#1022 Refactor parts of CafeteriaLocalRepository to prevent widget crash
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaMenuDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/repository/CafeteriaLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/widget/MensaRemoteViewFactory.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/widget/MensaWidget.java
  app/src/main/java/de/tum/in/tumcampusapp/service/MensaWidgetService.kt
Labels: Bug :bug:, review

#1020 Re-enable and fix calendar sync
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/service/FillCacheService.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/CacheManager.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Bug :bug:, review

#1027 Move to Retrofit for Cafeteria
  app/src/main/java/de/tum/in/tumcampusapp/api/cafeteria/CafeteriaAPIClient.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/cafeteria/CafeteriaAPIService.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/interceptors/CachingHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaMenuDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaMenuManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/model/CafeteriaMenu.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/model/CafeteriaResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/MainActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
Labels: Improvement, review

#1018 Do MVV calls with Retrofit
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/roomfinder/RoomFinderDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVSymbolView.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvApiService.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvClient.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvDateSerializer.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvDeparture.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvDepartureList.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvServingLine.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvStationList.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvStationListSerializer.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/StationResult.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/model/efa/WidgetDepartures.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/NetUtils.java
  app/src/test/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvDepartureListTest.java
  app/src/test/java/de/tum/in/tumcampusapp/component/ui/transportation/api/MvvStationListTest.java
Labels: Improvement, review

#1026 Move to Retrofit for Study Rooms
  app/schemas/de.tum.in.tumcampusapp.database.TcaDb/13.json
  app/src/main/java/de/tum/in/tumcampusapp/api/app/DateSerializer.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/Helper.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupManager.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsPagerAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/model/StudyRoom.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/model/StudyRoomGroup.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/Converters.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/java/de/tum/in/tumcampusapp/database/migrations/Migration12to13.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/NetUtils.java
  app/src/main/res/values/colors.xml
Labels: Improvement, review

#1025 Refactor grades activity
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/model/Exam.kt
  app/src/main/res/layout-land/activity_grades.xml
  app/src/main/res/layout/activity_grades.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: Improvement, review

#1035 Minor setup wizard fixes
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/WizNavCheckTokenActivity.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Improvement, review

#1023 Fix NullPointerException when clicking an event
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/IntegratedCalendarEvent.java
Labels: Bug :bug:, review

#1003 Ticket Sale: feedback from PR
  .idea/fileTemplates/includes/File Header.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/model/ChatVerification.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketEphemeralKeyProvider.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketTypeDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/EventDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/EventsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/TicketPaymentSelectActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/adapter/EventDetailsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/adapter/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Event.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/TicketType.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/EphimeralKey.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketPurchaseStripe.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservation.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservationCancelation.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketReservationResponse.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketStatus.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/payload/TicketSuccessResponse.kt
  app/src/main/res/layout/activity_payment_selection.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review
