Repository TUM-Dev/Campus-Android, pull requests merged in 2018-06, with the labels that each got.

#858 Fix text color of items in study rooms spinner
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomsActivity.java
  app/src/main/res/layout/activity_cafeteria.xml
  app/src/main/res/layout/activity_study_rooms.xml
  app/src/main/res/layout/simple_spinner_dropdown_item_actionbar.xml
Labels: review

#856 Update design of Settings
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/settings/SettingsFragment.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/settings.xml
Labels: review

#844 Picasso file caching
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/App.java
Labels: review

#861 Fix text in tuition fees card
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/model/Tuition.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Bug :bug:, review

#855 Change Observable chaining to prevent RxJava's UndeliverableException
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/repository/KinoLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/model/Kino.kt
Labels: review

#835 change grade background color programmatically
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/ExamListAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/model/Exam.kt
  app/src/main/res/drawable/grade_1_0.xml
  app/src/main/res/drawable/grade_1_3.xml
  app/src/main/res/drawable/grade_1_7.xml
  app/src/main/res/drawable/grade_2_0.xml
  app/src/main/res/drawable/grade_2_3.xml
  app/src/main/res/drawable/grade_2_7.xml
  app/src/main/res/drawable/grade_3_0.xml
  app/src/main/res/drawable/grade_3_3.xml
  app/src/main/res/drawable/grade_3_7.xml
  app/src/main/res/drawable/grade_4_0.xml
  app/src/main/res/drawable/grade_4_3.xml
  app/src/main/res/drawable/grade_4_7.xml
  app/src/main/res/drawable/grade_5_0.xml
Labels: review

#822 add user to chat room via search
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/app/Helper.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/feedback/FeedbackActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/AddChatMemberActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatRoomDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/MemberSuggestionsListAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/model/ChatMember.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/drawable/ic_action_search_black.xml
  app/src/main/res/layout/activity_add_chat_member.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#870 Set UI for Buy ticket confirmation page
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/res/layout/activity_buy_ticket.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#869 Fix odd animation in news settings
  app/src/main/java/de/tum/in/tumcampusapp/component/other/settings/SettingsFragment.java
Labels: review

#854 Refactor CardManager
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/TUMOnlineConst.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/widget/CardsWidgetService.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/settings/SettingsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/lectures/activity/LecturesPersonalActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeeManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaMenuCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaDetailsSectionFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/model/CafeteriaWithMenus.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/repository/CafeteriaLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatRoomController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatRoomsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/eduroam/SetupEduroamActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardsRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/MainActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/MainActivityViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/card/Card.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/card/NotificationAwareCard.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/card/ProvidesCard.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.java
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/CacheManager.java
Labels: review

#874 fix Kino lastId null
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/repository/KinoLocalRepository.kt
Labels: review

#868 Eventoverview bookedeventoverview
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/drawable/ic_action_booked.xml
  app/src/main/res/drawable/ic_all_event.xml
  app/src/main/res/drawable/ic_events.xml
  app/src/main/res/layout/activity_events.xml
  app/src/main/res/layout/card_events_item.xml
  app/src/main/res/menu/menu_activity_events.xml
  app/src/main/res/values-de/strings.xml
Labels: review

#875 Test Travis Build
  .travis.yml
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/App.java
  app/src/main/java/de/tum/in/tumcampusapp/TestApp.java
  app/src/test/java/de/tum/in/tumcampusapp/ChatMessageValidatorTestCase.java
  app/src/test/java/de/tum/in/tumcampusapp/RSASignerTestCase.java
  app/src/test/java/de/tum/in/tumcampusapp/activities/BaseActivityTest.java
  app/src/test/java/de/tum/in/tumcampusapp/activities/CurriculaActivityTest.java
  app/src/test/java/de/tum/in/tumcampusapp/activities/KinoActivityTest.kt
  app/src/test/java/de/tum/in/tumcampusapp/activities/MainActivityTest.java
  app/src/test/java/de/tum/in/tumcampusapp/activities/RoomFinderActivityTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/CalendarDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/NewsDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/NewsSourcesDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/RoomLocationsDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/migrations/PreRoomMigrationTest.kt
  app/src/test/java/de/tum/in/tumcampusapp/managers/SyncManagerTest.java
  app/src/test/java/de/tum/in/tumcampusapp/models/tumo/IdentityTest.kt
  build.gradle
Labels: review

#876 fix cut off image placeholder in drawer head
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/BaseActivity.java
  app/src/main/res/layout/drawer_header.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#882 Fix bug that occasionally caused transport search results to be empty
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.java
Labels: review

#881 Fix crash in TransportDetails
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVSymbolView.java
Labels: review

#867 disable crashlytics for debug and -dev builds
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/App.java
  app/src/main/java/de/tum/in/tumcampusapp/TestApp.java
  build.gradle
Labels: review

#885 Fix crashes when device is offline
  app/src/main/java/de/tum/in/tumcampusapp/api/app/ConnectivityInterceptor.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/Helper.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/exception/NoNetworkConnectionException.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/NetUtils.java
  app/src/main/res/drawable/news_source_placeholder.xml
  app/src/main/res/layout/card_news_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: review

#887 Payment Selection and Checkout
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketPaymentSelectActivity.java
  app/src/main/res/layout/activity_payment_selection.xml
  app/src/main/res/layout/activity_payment_stripe.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: FeatureBranch, review

#886 Update design of CreateEventActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarDetailsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/model/CalendarItem.kt
  app/src/main/res/layout/activity_create_event.xml
  app/src/main/res/layout/fragment_calendar_details.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: review

#837 Add animations to GradesActivity
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesActivity.java
  app/src/main/res/drawable/ic_arrow_anim_down.xml
  app/src/main/res/drawable/ic_arrow_anim_up.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/layout-land/activity_grades.xml
  app/src/main/res/layout/activity_grades.xml
  app/src/main/res/values/paths.xml
  app/src/main/res/values/strings.xml
Labels: User experience :rofl:, review

#891 Fix empty TUFilm screen
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/KinoViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/repository/KinoRemoteRepository.kt
Labels: review

#853 Created EventDetailsFragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketsController.java
  app/src/main/res/layout/card_events_item.xml
  app/src/main/res/layout/event_header.xml
  app/src/main/res/values/strings.xml
Labels: FeatureBranch, Work in progress, review

#897 Merge master into ticketsale
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/App.java
  app/src/main/java/de/tum/in/tumcampusapp/TestApp.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/ConnectivityInterceptor.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/Helper.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/exception/NoNetworkConnectionException.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/activity/BaseActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarDetailsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/model/CalendarItem.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVSymbolView.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/TransportController.java
  app/src/main/java/de/tum/in/tumcampusapp/utils/NetUtils.java
  app/src/main/res/drawable/ic_arrow_anim_down.xml
  app/src/main/res/drawable/ic_arrow_anim_up.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/news_source_placeholder.xml
  app/src/main/res/layout-land/activity_grades.xml
  app/src/main/res/layout/activity_create_event.xml
  app/src/main/res/layout/activity_grades.xml
  app/src/main/res/layout/card_news_item.xml
  app/src/main/res/layout/drawer_header.xml
  app/src/main/res/layout/fragment_calendar_details.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/paths.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: review

#880 Fix DB index error on first launch
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/test/java/de/tum/in/tumcampusapp/activities/KinoActivityTest.kt
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/CalendarDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/NewsDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/NewsSourcesDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/dao/RoomLocationsDaoTest.java
  app/src/test/java/de/tum/in/tumcampusapp/database/migrations/PreRoomMigrationTest.kt
  app/src/test/java/de/tum/in/tumcampusapp/managers/SyncManagerTest.java
Labels: review

#883 Prevent crash caused by WifiManager
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/service/NetworkChangeReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/ScanResultsAvailableReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/WifiScanHandler.kt
Labels: review

#902 Check which ids/keys/tokens have been uploaded and upload missing ones
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/app/AuthenticationManager.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/model/DeviceUploadFcmToken.kt
  app/src/main/java/de/tum/in/tumcampusapp/api/app/model/UploadStatus.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/general/FcmUpdate.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/general/NotificationDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/general/Update.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/alarm/AlarmActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/alarm/AlarmNotification.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/alarm/model/FcmAlert.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/alarm/model/FcmNotification.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/alarm/model/FcmNotificationLocation.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatMessageViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatNotification.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/FcmChat.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/activity/ChatActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/InformationActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/Converters.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/java/de/tum/in/tumcampusapp/service/FcmIdentificationService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/ScanResultsAvailableReceiver.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
Labels: review

#884 Add dedicated card layouts
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/tutionfees/TuitionFeesCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaMenuCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaMenuViewHolder.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/details/CafeteriaViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/model/CafeteriaWithMenus.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatMessagesCard.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/chat/ChatMessagesCardViewHolder.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/card/CardViewHolder.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/transportation/MVVCardViewHolder.kt
  app/src/main/res/layout/card_cafeteria_menu.xml
  app/src/main/res/layout/card_chat_messages.xml
  app/src/main/res/layout/card_mvv.xml
  app/src/main/res/layout/card_tuition_fees.xml
Labels: review

#921 Remove MVV plans functionality
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/plan/PDFViewActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/plan/PlanListAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/plan/PlansActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/plan/PlansDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/plan/PlansViewFragment.java
  app/src/main/res/drawable/ic_plans.xml
  app/src/main/res/layout/activity_plans.xml
  app/src/main/res/layout/activity_plans_listview.xml
  app/src/main/res/layout/activity_zoomable_image.xml
  app/src/main/res/layout/fragment_plans_view.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Improvement, review

#912 Improve ticket ui
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsAdapter.java
  app/src/main/res/layout/activity_events.xml
  app/src/main/res/layout/card_events_item.xml
  app/src/main/res/layout/event_fragment.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review

#922 add Event to calendar
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsFragment.java
  app/src/main/res/layout/event_header.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#923 Improve show ticket
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Ticket.kt
  app/src/main/res/drawable-nodpi/qr_code_demo.png
  app/src/main/res/layout-land/activity_show_ticket.xml
  app/src/main/res/layout/activity_show_ticket.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: review

#924 Implemented local database for events
  app/schemas/de.tum.in.tumcampusapp.database.TcaDb/10.json
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketTypeDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Event.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/Ticket.kt
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
Labels: review

#925 Prevent NullPointerException in EduroamCard
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/eduroam/EduroamCard.java
Labels: Bug :bug:, review

#926 Fix unnecessary comma in grades list items
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/ExamListAdapter.java
  app/src/main/res/layout/activity_grades_listview.xml
Labels: Improvement, review

#866 remove Curricula, since since we're overhauling them
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/other/generic/drawer/DrawerMenuHelper.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/curricula/CurriculaActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/curricula/CurriculaDetailsActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/curricula/CurriculumAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/curricula/model/Curriculum.kt
  app/src/main/res/layout/activity_curricula.xml
  app/src/main/res/layout/activity_curriculadetails.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/de/tum/in/tumcampusapp/activities/CurriculaActivityTest.java
Labels: review

#932 Bump database version
  app/schemas/de.tum.in.tumcampusapp.database.TcaDb/11.json
  app/src/main/java/de/tum/in/tumcampusapp/database/TcaDb.java
Labels: Bug :bug:, review

#936 Fix exception occurring in Picasso image loading
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsCard.java
Labels: Bug :bug:, review
