Repository TUM-Dev/Campus-Android, pull requests merged in 2019-01, with the labels that each got.

#1243 Fix time selection for custom events
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CreateEventActivity.java
Labels: Bug :bug:

#1242 Fix custom email in Feedback
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/feedback/FeedbackActivity.java
  app/src/main/res/layout/activity_feedback.xml
Labels: Bug :bug:

#1241 Refactor EventsViewModel and introduce dependency injection
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeAPIService.java
  app/src/main/java/de/tum/in/tumcampusapp/api/app/TUMCabeClient.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/CardsRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventCard.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventCardsProvider.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsController.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsViewState.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/TicketDao.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/BuyTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/ShowTicketActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/StripePaymentActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/adapter/EventsAdapter.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/di/EventId.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/di/TicketsComponent.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/di/TicketsModule.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventDetailsViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/repository/EventsLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/repository/EventsRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/repository/TicketsLocalRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/repository/TicketsRemoteRepository.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoDetailsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoDetailsViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/di/KinoModule.kt
  app/src/main/java/de/tum/in/tumcampusapp/di/AppComponent.kt
  app/src/main/java/de/tum/in/tumcampusapp/di/AppModule.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/di/DownloadModule.kt
Labels: Improvement

#1244 Show notifications for new grades
  app/src/main/java/de/tum/in/tumcampusapp/component/notifications/persistence/NotificationType.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesActivity.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesBackgroundUpdater.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesNotificationProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/GradesStore.kt
  app/src/main/java/de/tum/in/tumcampusapp/di/AppModule.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/DownloadService.kt
  app/src/main/java/de/tum/in/tumcampusapp/service/di/DownloadModule.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Feature :tada:

#1248 Fix issue where dismissed TopNewsCard would appear again
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/TopNewsStore.kt
Labels: Bug :bug:

#1252 Fixes mismatch between selected event and the movie that is displayed
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoDao.java
Labels: Bug :bug:
