Repository TUM-Dev/Campus-Android, pull requests merged in 2019-03, with the labels that each got.

#1269 Improve placeholders
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/fragment/EventsFragment.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/model/EventType.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/tufilm/KinoDetailsFragment.java
  app/src/main/res/drawable/popcorn_placeholder.xml
  app/src/main/res/drawable/tickets_placeholder.xml
  app/src/main/res/layout/card_events_item_vertical.xml
  app/src/main/res/layout/fragment_events.xml
  app/src/main/res/layout/fragment_kinodetails_section.xml
Labels: User experience :ok_hand:

#1267 Fix Grades 'Unknown error'
  app/build.gradle
  app/src/main/java/de/tum/in/tumcampusapp/api/tumonline/converters/DateTimeConverter.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/tumui/grades/ExamListAdapter.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: Bug :bug:

#1268 Fix Mensa widget
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/widget/MensaWidget.java
Labels: Bug :bug:

#1271 Fix pull-to-refresh issue in events view
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsViewModel.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/EventsViewState.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/ticket/activity/EventsActivity.java
  app/src/main/java/de/tum/in/tumcampusapp/service/di/DownloadComponent.kt
Labels: Bug :bug:

#1279 Show multiple chosen cafeteria cards
  app/src/main/java/de/tum/in/tumcampusapp/component/other/locations/LocationManager.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/other/settings/SettingsFragment.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaMenuCard.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/CafeteriaNotificationProvider.kt
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/cafeteria/controller/CafeteriaManager.java
  app/src/main/java/de/tum/in/tumcampusapp/component/ui/overview/card/Card.kt
  app/src/main/java/de/tum/in/tumcampusapp/utils/Const.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: Feature :tada:
